# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ActionDemo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build-project:
    runs-on: windows-2019

    steps:      
    - uses: actions/checkout@v2    

    
    - name: setup-msbuild 
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
      
    - name:  Restore Nuget Packages
      run: nuget restore WebApplication1/WebApplication1.sln
      
    - name: Build
      run: msbuild WebApplication1/WebApplication1.sln /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

    - name: deleteing
      run: |
           del "./_build/bin/*.*"

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       name: release-artifact-${{ github.event.release.name }}
       path: ./_build

  release-project:
    name: Release Project
    if: github.event.ref== 'refs/heads/main'
    runs-on: windows-2019
    needs: build-project
    steps:
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: release-artifact-${{ github.event.release.name }}

    - name: Test artifacr download
      run: ls -R
    

