name: Deploy to production
on:
  workflow_dispatch:
    inputs:
      release:
        description: Name of release to deploy
        required: true
        default: v1.0.0

jobs:
  release-project:
    name: Release Project
    runs-on: windows-2019
    steps:
    - name: Download the release artifact
      uses: actions/download-artifact@v2
      with:
        name: release-${{ github.event.inputs.release }}
        path: ./_build

    - name: Test artifacr download
      run: ls -R
